---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
library(janitor)
theme_set(theme_bw())
```

```{r}
dados_raw = read_csv(
    here::here("./vis-cultura-stackoverflow/data/participation-per-country.csv"),
    col_types = cols(
        .default = col_double(),
        site = col_character(),
        country = col_character(),
        geo = col_character(),
        four_regions = col_character(),
        eight_regions = col_character(),
        six_regions = col_character(),
        `World bank income group 2017` = col_character()
    )
) %>% janitor::clean_names()


dados_raw$responderam_prop = dados_raw$responderam_prop* 100

dados = dados_raw %>% 
    filter(usuarios > 200, site == "StackOverflow") 

dadosSuper = dados_raw %>% 
    filter(usuarios > 200, site == "SuperUser")

glimpse(dados)

glimpse(dadosSuper)
```
```{r}
dados %>% 
    skim()
```

```{r}
dados %>% 
    ggplot(aes(x = epi, y = responderam_prop)) + 
    geom_point(size = 6)
```

```{r}
dados %>% 
    filter(!is.na(epi), responderam_prop < .41, epi > 45)
```
```{r}
dados %>% 
    ggplot(aes(x = pdi, y = responderam_prop)) + 
    geom_point(size = 6, alpha = .4)
```

```{r}
dados %>% 
    ggplot(aes(x = longitude, responderam_prop)) + 
    geom_point(size = 6, alpha = .5)
```

```{r}
dados %>% 
    mutate(aleatoria = runif(n())) %>% 
    ggplot(aes(x = aleatoria, y = responderam_prop)) + 
    geom_point(size = 5)
```


```{r}
dados %>% 
    mutate(muito_parecida = -2 * responderam_prop + runif(n(), min = .1, max = .75)) %>% 
    ggplot(aes(x = muito_parecida, y = responderam_prop)) + 
    geom_point(size = 5)
```

```{r}
dados %>% 
    filter(!is.na(gni)) %>% 
    ggplot(aes(x = gni, y = responderam_prop)) +
    geom_point(size = 6, alpha = .5)
```

```{r}
dados %>% 
    filter(!is.na(gni)) %>% 
    ggplot(aes(x = gni, y = responderam_prop)) +
    geom_point(size = 6, alpha = .5) + 
    scale_x_log10()
```

Então existe uma relação linear entre atuação e log_10(gni). 

```{r}
dados %>% 
    filter(!is.na(gni)) %>% 
    mutate(gni_log = log10(gni)) %>% 
    ggplot(aes(x = gni_log, y = responderam_prop)) +
    geom_point(size = 6, alpha = .5) 
```
```{r}
m1 = lm(responderam_prop ~ epi + log10(gni) + internet, data=dados)

t = tidy(m1, conf.int = T)
t
glance(m1)
```

```{r}
m1 %>% augment(newdata = dados) %>% 
  ggplot(aes(x = .fitted))+
  geom_point(aes(y=.resid), alpha=.5) +
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title = "Resíduos Modelo 1",
    x = "Predição",
    y = "Resíduo"
  )

tidy(m1, conf.int = T) %>% 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             ymin=conf.low,
             ymax=conf.high))+
  geom_linerange() +
  geom_point()+
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title= "IC Coeficientes dos Termos. Modelo 1",
    x = "Termo",
    y = "IC Coeficiente"
  )+
  coord_flip()
  
```


```{r}
m2 = lm(responderam_prop ~ epi + log10(gni) + internet + idv, data=dados)

tidy(m2, conf.int = T)
glance(m2)
```


```{r}
m2 %>% augment(newdata = dados) %>% 
  ggplot(aes(x = .fitted))+
  geom_point(aes(y=.resid), alpha=.5) +
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title = "Resíduos Modelo 2",
    x = "Predição",
    y = "Resíduo"
  )

tidy(m2, conf.int = T) %>% 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             ymin=conf.low,
             ymax=conf.high))+
  geom_linerange() +
  geom_point()+
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title= "IC Coeficientes dos Termos. Modelo 2",
    x = "Termo",
    y = "IC Coeficiente"
  )+
  coord_flip()
```



```{r}
m3 = lm(dadosSuper$responderam_prop ~ dadosSuper$epi + log10(dadosSuper$gni) + dadosSuper$internet + dadosSuper$idv)

tidy(m3, conf.int = T)
glance(m3)
```


```{r}
m3 %>% augment(newdata = dadosSuper) %>% 
  ggplot(aes(x = .fitted))+
  geom_point(aes(y=.resid), alpha=.5) +
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title = "Resíduos Modelo 3",
    x = "Predição",
    y = "Resíduo"
  )

tidy(m3, conf.int = T) %>% 
  ggplot(aes(x = reorder(term, estimate),
             y = estimate,
             ymin=conf.low,
             ymax=conf.high))+
  geom_linerange() +
  geom_point()+
  geom_hline(yintercept = 0, color = "red")+
  labs(
    title= "IC Coeficientes dos Termos. Modelo 3",
    x = "Termo",
    y = "IC Coeficiente"
  )+
  coord_flip()
```

```